application: orator-gae
#module: #your module#
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# handlers:
# - url: .*
#   script: main.bottle

# webapp2
handlers:
- url: .*
  script: route_table.application  


libraries:
- name: MySQLdb
  version: "latest"
